# Generated by Django 4.1.2 on 2024-08-22 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oar", "0001_squashed_0100_alter_indication_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="file_hash",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="objective",
            name="comparison_sym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparison_sym",
                to="oar.comparisonsym",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="desc",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="reference",
            name="url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vue",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
