# Generated by Django 4.1.2 on 2024-08-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oar", "0101_reference_file_hash_alter_objective_comparison_sym_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indication",
            name="linked_with",
            field=models.ManyToManyField(blank=True, to="oar.indication"),
        ),
        migrations.AlterField(
            model_name="indicationorg",
            name="constraints",
            field=models.ManyToManyField(
                related_name="indicationOrg_cons", to="oar.objective"
            ),
        ),
    ]
