# Generated by Django 4.1.2 on 2024-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oar", "0102_alter_indication_linked_with_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
